# https://github.com/JIghtuse/cavestory-sdl2/blob/master/.travis.yml
language: cpp
compiler:
  - gcc

before_install:
  - sudo apt-add-repository --yes ppa:zoogie/sdl2-snapshots       # libsdl2
  - sudo apt-get -qq update
  #~ - sudo apt-get install -y libsdl2-gfx-dev libsdl2-image-dev  libsdl2-mixer-dev  libsdl2-ttf-dev
  - sudo apt-get install -y libsdl2-image-dev  libsdl2-mixer-dev  libsdl2-ttf-dev

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
